add basics for doing auth use case testing
aztfmod/rovergo pull request #112
Opened 2021-06-18 16:21 UTC by sebastus

add  necessary az commands & a couple of tests, remove a few CheckError statements.

2021-06-18 17:29 UTC, hattan requested changes

2021-06-18 17:29 UTC, hattan commented on pkg/testing/cli.go
> +	console.Debugf("Loading test config from: testConfig.yaml\n")
Instead of a yaml file. Can we load these from environment variables and use https://github.com/joho/godotenv for local dev?

This will make running integration tests in pipelines easier.

2021-06-18 17:39 UTC, sebastus commented on pkg/testing/cli.go
> +	console.Debugf("Loading test config from: testConfig.yaml\n")
done

2021-06-18 19:13 UTC, hattan approved these changes
LGTM

2021-06-21 14:02 UTC, benc-uk approved these changes

2021-06-22 08:36 UTC, merged