load commands yml file and validates it
aztfmod/rovergo pull request #133
Opened 2021-09-23 05:09 UTC by polatengin

With the changes, rovergo now loads `commands.yaml` file if it finds it in the **current working directory** or in the **rover home directory**

It validates the custom commands and groups structures by

- checking if the names are duplicate
- checking if command names are already exists in the builtin commands list

Fixes,

- [Rover should load custom commands from commands.yaml file](https://dev.azure.com/csedevops/TeamBoard/_workitems/edit/2841/)
- [Rover should validate commands.yaml upon startup](https://dev.azure.com/csedevops/TeamBoard/_workitems/edit/2844/)
- [Add Group commands to auto-generated help (cli usage)](https://dev.azure.com/csedevops/TeamBoard/_workitems/edit/2847/)

To check if the changes are working; I created `commands.yaml` file at the root of the project with the following content;

```yaml
commands:
  format:
    executableName: "terraform"
    subCommand: "fmt"
    flags: "-no-color -recursive -check -diff"
    debug: false
    requiresInit: false
    parameters:
      - name: list
        value: true
        prefix: "-"
      - name: write
        value: false
        prefix: "-"
  format2:
    executableName: "terraform"
    subCommand: "fmt"
    flags: "-no-color -recursive -check -diff"
    debug: false
    requiresInit: false
    parameters:
      - name: list
        value: true
        prefix: "-"
      - name: write
        value: false
        prefix: "-"

groups:
  deploy:
    - format
    - foo
    - plan
    - apply
    - test
  validate:
    - plan
    - apply
    - security
    - unit
    - int
```

2021-09-23 14:11 UTC, hattan requested changes
Thanks for the contribution, @polatengin . This looks great. Just a few small points.

* Can we we please add custom commands to the root README and also to docs (either a new doc file and/or user-guide.md?
* Can we provide an example commands.yaml in the examples folder?
* Can we add unit tests to ensure the new command code is covered by tests?

Thanks!

2021-09-23 14:11 UTC, hattan commented on pkg/custom/commands.go
> +			return errors.New("custom command name cannot be the same as a builtin command")
Would it be possible to include the name of the custom command and the builtin command that collided? This will make it easier for users that add several custom commands at once to know which one is causing problems.

2021-09-23 14:11 UTC, hattan commented on pkg/custom/commands.go
> +			return errors.New("group name cannot be the same as a builtin command")
Same as with the previous comment, can we provide details in the error message on which group name is causing an issue?

2021-09-23 19:50 UTC, polatengin commented on pkg/custom/commands.go
> +			return errors.New("custom command name cannot be the same as a builtin command")
I used `fmt.Errorf()` method instead and added the name of the custom command.

2021-09-23 19:50 UTC, polatengin commented on pkg/custom/commands.go
> +			return errors.New("group name cannot be the same as a builtin command")
I used `fmt.Errorf()` method instead and added the name of the group command.

2021-09-24 04:01 UTC, polatengin commented
> Thanks for the contribution, @polatengin . This looks great. Just a few small points.
> 
> * Can we we please add custom commands to the root README and also to docs (either a new doc file and/or user-guide.md?
> * Can we provide an example commands.yaml in the examples folder?
> * Can we add unit tests to ensure the new command code is covered by tests?
> 
> Thanks!

Hey @hattan, created a few new commits to resolve these issues. could you please review those changes?

Bests,
Engin.

2021-09-29 21:03 UTC, hattan approved these changes
LGTM

2021-09-29 21:03 UTC, merged