parse symphony.yml in ci command
aztfmod/rovergo pull request #27
Opened 2021-05-28 14:30 UTC by sebastus

so the values in the config can be used in the program

--symphony-config can be aliased as --sc or -c

2021-05-28 15:10 UTC, benc-uk requested changes
Some feedback

2021-05-28 15:10 UTC, benc-uk commented on sample.symphony.yaml
> +environment: prod
Maybe move this to an etc/ or samples/ folder in the repo? root is already getting cluttered?

2021-05-28 15:10 UTC, benc-uk commented on cmd/ci.go
> +type SymphonyConfig struct {
How about moving this into pkg/symphony ?
I expect a bunch of other things might need it down the line

2021-05-28 15:10 UTC, benc-uk commented on cmd/ci.go
> +		if verbose {
There's already a flag in pkg/console to handle this, so they can pass --debug to any command
And then in the code we call `console.Debug("this is only shown when debug is set!!")`

2021-05-28 15:10 UTC, benc-uk commented on cmd/ci.go
> +	color.Red("Running CI command, config: %s", symphonyConfigFileName)
Replace with console.Error or console.Info etc 
See pkg/console it's pretty simple

2021-05-28 15:16 UTC, sebastus commented on sample.symphony.yaml
> +environment: prod
done. also moved .rover.sample.yaml

2021-05-28 16:13 UTC, sebastus commented on cmd/ci.go
> +		if verbose {
done

2021-05-28 16:14 UTC, sebastus commented on cmd/ci.go
> +type SymphonyConfig struct {
done. also made it an OOP.

2021-05-28 16:15 UTC, sebastus commented on cmd/ci.go
> +	color.Red("Running CI command, config: %s", symphonyConfigFileName)
done

2021-05-28 16:23 UTC, sebastus commented
strictly speaking, it's not necessary to parse symphony.yml in the top level ci command. but the ci commands are in another issue. So when this pr is merged and I get to the next one, I'll move the parse down to the sub-commands.

2021-06-01 08:48 UTC, benc-uk approved these changes

2021-06-01 09:04 UTC, merged