Complete restructure
aztfmod/rovergo pull request #79
Opened 2021-06-11 15:53 UTC by benc-uk

Complete restructure and refactor

2021-06-12 10:23 UTC, sebastus requested changes
so much better structurally! great work!

2021-06-12 10:23 UTC, sebastus commented on cmd/root.go
> +					cobra.CheckErr("--config and --config-dir options must not be combined, specify only one")
--config-file and --config-dir  ??

2021-06-12 10:23 UTC, sebastus commented on pkg/landingzone/cobra.go
> +	if ws == "" {
extract defaults to const?

2021-06-12 10:23 UTC, sebastus commented on pkg/landingzone/cobra.go
> +		env = "sandpit"
same

2021-06-12 10:23 UTC, sebastus commented on pkg/landingzone/landingzone.go
>  const secretLowerSAName = "lower-storage-account-name"
export consts? - they might be needed elsewhere - for example I used secretTenantID in a test

2021-06-12 11:53 UTC, sebastus commented
Can we further isolate config and execute? Something like this:

pkg/landingzone/cobra.go:
`func RunFromCLI(cmd *cobra.Command, action Action) *[]Options {
...
   return []Options{opt}
}`

pkg/symphony/cobra.go
`func RunFromConfig(cmd *cobra.Command, action landingzone.Action) *[]Options {
...
	if levelName == "" {
		return conf.runAll(action, dryRun)  <-- returns array of Options
	}
...
	return conf.RunLevel(*level, action, dryRun)  <-- returns array of Options
`

root.go
`var options []Options
if configFile != "" {
	options = symphony.RunFromConfig(cmd)
} else {
	options = landingzone.RunFromCLI(cmd)
}

for _, optionSet := range options {
	_ = action.Execute(optionSet)
}
console.Success("Rover has finished")
os.Exit(0)
`

Then, a test can do the initial bit to build the options array and assert on its contents without running execute. An integration test can go on to run Execute and check the actual resources.

2021-06-14 09:13 UTC, benc-uk commented on pkg/landingzone/cobra.go
> +		env = "sandpit"
Good idea

2021-06-14 09:13 UTC, benc-uk commented on cmd/root.go
> +					cobra.CheckErr("--config and --config-dir options must not be combined, specify only one")
Good catch

2021-06-14 09:26 UTC, benc-uk commented on pkg/landingzone/landingzone.go
>  const secretLowerSAName = "lower-storage-account-name"
done

2021-06-14 09:33 UTC, sebastus approved these changes
lgtm

let's merge it and deal with whatever's left in another PR.

2021-06-14 10:29 UTC, sebastus approved these changes
lgtm

2021-06-14 11:01 UTC, merged